<?php

namespace Api\BlogPost\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BlogPostCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => ['required' , 'string'],
            'content' => ['required' , 'string'],
            'description' => ['nullable' , 'string'],
            'slug' => ['required','regex:/^[a-zA-Z0-9-_]+$/', 'unique:blog_posts,slug'],
            "categories" => ['required' , 'array'],
            'categories.*' => ['required' , 'exists:categories,id'],
            'thumbnail' => ['required', 'image', 'mimes:jpg,png,jpeg,webp', 'max:2048'],
            "tags" => ['required' , 'array'],
            "tags.*" => ['required'],
        ];
    }

    public function validated($key = null, $default = null)
    {
        $data = parent::validated($key, $default); // TODO: Change the autogenerated stub

        $data['created_by'] = \Auth::id();

        return $data;
    }
}
